---
title: "RDSCreationAndMergeData"
author: "Mehmet AK"
date: "11 11 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
```

# Data Merging
```{r body}
main_data <- tibble()
tmprds <- tempfile(fileext=".rds")

print("Getting 2018-09 data from repository")
download.file("https://github.com/MEF-BDA503/mef-bda503.github.io/blob/master/files/car_data_sep_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-07 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-busraakoc/blob/master/odd_car_sales_data_jul_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-06 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-muharremcakir81/blob/master/Week2/Odd_Retail_Sales_201806.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-05 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-EmreKemerci/blob/master/AssignmentWeek2/data_may_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-04 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-omerbayir/blob/master/week2/odd_car_sales_data_april_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-02 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-aturhal/blob/master/odd_car_sales_data_feb_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

print("Getting 2018-01 data from repository")
download.file("https://github.com/MEF-BDA503/pj18-SerhanSuer/blob/master/odd_car_sales_data_jan_18.rds?raw=true",destfile=tmprds)
main_data <- bind_rows(main_data,readRDS(tmprds))

# Save the final merged RDS file
saveRDS(main_data,file="/Users/macboookair/Desktop/bda/pj18-mkaracabey/MergeDataAndAnalysis/car_data_aggregate.rds")

# Remove temporary file
file.remove(tmprds)
```
# Analysis
```{r analysis}
head(main_data)
```

```{r ,warning=FALSE}
main_data %>% select(brand_name,auto_dom) %>% filter(auto_dom>0)
```

```{r ,warning=FALSE}
main_data %>%
    group_by(month) %>%
    filter(auto_total>3000) %>%
    slice(1:10)
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
ggplot(data = main_data,aes(x=brand_name,y=auto_dom))+ geom_point()
```


